name: Build-snapshots
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java Temurin 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Install Gradle
      uses: gradle/gradle-build-action@v3
      with:
          gradle-version: wrapper # 自动检测 wrapper 指定的版本

    - name: Build with installed Gradle
      run: gradle build --no-daemon --stacktrace
      
    - name: Cache Gradle dependencies # 缓存依赖加速构建
      uses: actions/cache@v3
      with:
        path: |
          ~\.gradle\caches
          ~\.gradle\wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
