name: Build-snapshots
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境执行 gradlew.bat

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Java Temurin 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Grant execute permission to gradlew
      run: icacls gradlew.bat /grant Everyone:F  # 确保批处理文件有执行权限

    - name: Build with Gradle
      run: .\gradlew.bat build
